### ISSUE TITLE
Refill: unexpected behavior when removing the currently selected item from the hotbar

### ISSUE THREAD

**Issue by MXMLNDML** [dthigpen/dtcraft-datapacks#2] opened 2021-08-12 15:11 UTC
Hey, I just installed your refill data pack and noticed some unexpected behavior:

- removing the currently selected item by shift-clicking is not possible → the item is immediately placed in the same slot again

![example](https://user-images.githubusercontent.com/42516330/129220785-1b8c6eec-261b-4bb3-bd10-66e97539b9be.gif)
_pickaxe is held in main hand_
- if there is another stack of the currently selected item in the inventory clicking the stack in the hotbar causes the second stack to be placed in the selected hotbar slot

![example](https://user-images.githubusercontent.com/42516330/129220828-e566fe5a-0198-4d21-a7d7-be02b24a8ffc.gif)
_cobblestone is held in main hand_

_the reduced frame rate of the gifs caused that you can't really see the effects of shift clicking (doesn't show how the item flashes in the first available inventory slot)_

**Comment by dthigpen** [comment] 2021-08-13 13:30
Interesting I will look into some solutions for these soon. The shift click with only one item behavior can likely be fixed pretty easily. As for the second example, technically everything is working as intended. If I'm not mistaken, the current command API does not allow for a way to detect what a player is holding (with their cursor) so the datapack interprets it as being dropped. It then replaces it with the new stack. I'll definitely experiment with some solutions.

Also thanks for the detailed issue with the description and gif examples, much appreciated!

**Comment by dthigpen** [comment] 2021-08-16 15:07
Next release will include the shift-click fix along with a fix for the second issue that will make the case much less common. Basically there is a check for the stack size that was dropped. If the stack size is greater than 1 then it will not refill. So in your example 34 or 64 will not cause a refill. This allows it to still work for block placement or dropping individual items since it will go down by one each time. The downside is that this can still happen with single item stacks such as tools. I am working on durability mechanics for those cases though, but that will be in a later release.

I'll reply back when the release is out

**Comment by dthigpen** [comment] 2021-08-18 12:48
Release [v0.0.8](https://github.com/dthigpen/dtcraft-datapacks/releases/tag/v0.0.8) includes this fix. Let me know if you have any more improvements

**Closed** 2022-01-06 23:30 UTC
